apiVersion: v1
kind: Secret
metadata:
  name: camunda-credentials
type: Opaque
stringData:
  identity-keycloak-admin-password: keycloak-local-admin
  identity-keycloak-postgresql-admin-password: keycloak-postgresql-local
  identity-keycloak-postgresql-user-password: keycloak-postgresql-local
  identity-postgresql-admin-password: camunda-postgresql-local
  identity-postgresql-user-password: camunda-postgresql-local

