apiVersion: v1
kind: Secret
metadata:
  name: {{ include "local-keycloak.fullname" . }}
  labels:
    {{- include "local-keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.auth.adminPassword | quote }}
  database-password: {{ .Values.database.password | quote }}

