apiVersion: v1
kind: Secret
metadata:
  name: {{ include "local-postgresql.fullname" . }}
  labels:
    {{- include "local-postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.auth.password | quote }}

